sudo: required

os:
  - osx
  - linux
  - windows

language: go
go:
  - "1.11.x"
go_import_path: v2ray.com/core

git:
  depth: 5

before_script:
  - uname -a
  - date

script:
  - go test -p 1 -tags json -v v2ray.com/core/...

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./testing/coverage/coverall; fi
